### ISSUE TITLE
Markdown mode doesn't convert HTML

### ISSUE THREAD

**Issue by dev027** [jglev/obsidian-paste-mode#23]
Setting the clipboard to

    <h2>My heading</h2>
    <p>My paragraph</p>

and then doing a "Paste Mode: Paste in Markdown Mode" does not convert the clipboard to markdown before pasting. I would expect it to convert to

    ## My Heading

    My paragraph

But instead I just get

    <h2>My heading</h2>
    <p>My paragraph</p>

Doing "Paste Mode: Paste in Code Block Mode" works, and surrounds the clipboard contents with ```

Windows 10. Paste Mode plugin version 5.0.0

**Comment by jglev** [comment]
Thank you for reaching out! (And thank you also for noting your OS and version number!)

> Setting the clipboard to
> 
> ```
> <h2>My heading</h2>
> <p>My paragraph</p>
> ```

Just to confirm, are you copying the literal text ("`<h2>...`") you wrote out? Or are you copying the rendered HTML content from a web browser, like in this screenshot?

![image](https://user-images.githubusercontent.com/3667562/211174187-40be6b42-3d25-4939-a59a-3a2be8c3bc90.png)

If the former, this perhaps points more to a gap in the plugin's documentation than to unexpected (from my perspective as plugin author) behavior. The Markdown mode is (at least currently) meant to convert _rendered_ HTML to markdown; rendered HTML seems to get enriched beyond just the text itself when copying it from a web browser. Specifically, when copying the raw text to the clipboard, the browser (at least in a test just now using Firefox in Linux) copies the text as type `text/plain`, rather than as type `text/html`.

For the plugin to infer that `text/plain` is HTML _feels_ as though it might be a fraught path, as might adding an additional paste mode specifically for converting copied raw HTML; with that in mind, and considering that raw HTML will still render correctly in a markdown document, I'd like to leave this Issue open for a while to think more on its implications, currently leaning towards not supporting this specific use-case.

In the meantime, if you copy the raw HTML from an HTML file that's been opened in a web browser, the plugin _should_ convert that content to markdown. (It does on my systems across Linux and Windows -- would you be willing to confirm whether that works on your system, as well?)

Again, thank you for reaching out!

**Comment by jglev** [comment]
I'm going to close this Issue for now for lack of additional information; however, please do feel free to correspond more here! We can always re-open it later.
